ignore:
  - "examples/*"
coverage:
  status:
    patch:
      default:
        target: 80%
    project:
      default:
        target: 95%
fixes:
  - "MCintegration.py/MCintegration.py/::MCintegration.py/"
